print(1)
print(1, 2, 3)
print(1 + 1)
print(3 * 8)
print(10 - 2.2)
print(3 + (4 + 6) * 8 / 2 - 1)
print('*' * 80)
print("hello" + "" + "pyladies!")
print("sum of numbers 3 and 8 is", 3 + 8)
print('twinkle, twinkle, little star')
print("how i wonder what you are")
